### ISSUE TITLE
Get an error with the parameter extrafootnotefeatures in package xepersian version 25.5

### ISSUE THREAD

**Issue by maryamstat** [xepersian/bidi#3]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/xepersian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/xepersian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{report}

\usepackage[extrafootnotefeatures]{xepersian}

\settextfont{Yas}

\begin{document}

مقداری متن

\end{document}
![log](https://github.com/user-attachments/assets/9e295c86-df63-4da5-b71d-14868f17ebed)

```

**Comment by v-khalighi** [comment]
Thanks for your bug report. I have uploaded version 25.6 of the `xepersian` package to CTAN which should fix this issue.

I have also uploaded version 40.7 of the `bidi` package to CTAN but the `bidi` package had really nothing to do with this issue.
